import os
from gws_core import (
    ConfigParams, AppConfig, AppType, OutputSpec, OutputSpecs, StreamlitResource, Task, TaskInputs, TaskOutputs,
    app_decorator, task_decorator, TypingStyle
)


@app_decorator("BiolectorDashboardAppConfig", app_type=AppType.STREAMLIT,
               human_name="Generate Biolector Dashboard app")
class BiolectorDashboardAppConfig(AppConfig):
    """
    Configuration class for the Biolector Dashboard Streamlit application.

    This class defines the configuration and setup for a Streamlit-based dashboard
    that provides visualization and analysis capabilities for Biolector XT data.
    """

    def get_app_folder_path(self):
        """Get the path to the app folder relative to this file."""
        return self.get_app_folder_from_relative_path(__file__, "_biolector_dashboard")


@task_decorator("GenerateBiolectorDashboard", human_name="Generate Biolector Dashboard app",
                short_description="Create a Streamlit dashboard for Biolector XT data analysis",
                style=StreamlitResource.copy_style())
class GenerateBiolectorDashboard(Task):
    """
    Task that generates the Biolector Dashboard app.
    This dashboard provides visualization and analysis capabilities for Biolector XT data.

    The Biolector Dashboard is a Streamlit application designed for fermentation data analysis
    and visualization from Biolector XT instruments. It provides an interactive interface for
    processing, analyzing, and interpreting data from Biolector experiments through various
    analytical workflows.

    The aim is to simplify the use of the Biolector data processing by providing an application
    that makes uploading, processing, and visualizing fermentation data easier.

    Features:

    - **File Upload Interface**: Upload Excel files generated by Biolector XT
    - **Data Processing**: Automated processing using BiolectorXT task
    - **Data Quality Assessment**: Identification of missing values and incomplete datasets
    - **Interactive Selection**: Choose specific samples for detailed analysis
    - **Data Visualization**: Multiple chart types including time series, box plots, histograms, and scatter plots
    - **Statistical Analysis**: Descriptive statistics and data summaries
    - **Batch Analysis**: Compare different fermentation batches and culture conditions

    Required Input File:
    - Biolector Excel File: .xlsx or .xls file generated by Biolector XT containing measurement data

    The dashboard automatically processes uploaded files, identifies data quality issues,
    and provides an intuitive interface for selecting and visualizing specific datasets
    of interest for detailed analysis.
    """

    output_specs: OutputSpecs = OutputSpecs({
        'dashboard': OutputSpec(StreamlitResource, human_name="Biolector Dashboard")
    })

    def run(self, params: ConfigParams, inputs: TaskInputs) -> TaskOutputs:
        """Generate and return the Biolector Dashboard Streamlit application."""

        dashboard = StreamlitResource()
        dashboard.set_app_config(BiolectorDashboardAppConfig())

        return {"dashboard": dashboard}
