from gws_core import (InputSpec, OutputSpec, InputSpecs, OutputSpecs, Table, ListParam, Tag,
                      TypingStyle, ResourceSet, Task, task_decorator, ConfigSpecs, ConfigParams)
from typing import Dict, Any, List
import json


BATCH_TAG_KEY = "batch"
SAMPLE_TAG_KEY = "sample"


@task_decorator("FilterFermentorAnalyseLoadedResourceSetBySelection",
                human_name="Filter Fermentor Analyse ResourceSet by Selection",
                short_description="Filter ResourceSet based on Batch/Sample selection for Fermentalg analysis",
                style=TypingStyle.community_icon(icon_technical_name="filter", background_color="#28a745"))
class FilterFermentorAnalyseLoadedResourceSetBySelection(Task):
    """
    [Generated by Task Expert Agent]

    Filter ResourceSet based on user selection of Batch/Sample pairs for Fermentalg analysis.

    This task filters resources within a ResourceSet by examining their tags to match
    selected batch/sample combinations. Only resources with matching 'batch' and 'sample'
    tags are included in the filtered output.

    ## Usage
    - **Input**: ResourceSet containing fermentalg data with 'batch' and 'sample' tags on resources
    - **Output**: Filtered ResourceSet containing only resources matching the selection criteria
    - **Configuration**: List of batch/sample pairs to include

    ## Selection Criteria Format
    ```python
    {
        'couple0': {
            'batch': 'batch01',
            'sample': 'A1'
        },
        'couple1': {
            'batch': 'batch01',
            'sample': 'B1'
        },
        'couple2': {
            'batch': 'batch02',
            'sample': 'A1'
        },
    }
    ```

    ## Tag-Based Filtering
    - Each resource in the input ResourceSet is examined for 'batch' and 'sample' tags
    - Only resources with both tags matching the selection criteria are included
    - Resources missing either tag are excluded with a warning message
    - Original resources are preserved with all their tags and properties

    ## Notes
    - Resources must have both 'batch' and 'sample' tags to be considered for filtering
    - Tag values are matched exactly (case-sensitive)
    - Only Table resources are filtered; other resource types are ignored
    - Designed to work with output from FermentalgLoadData task
    """

    input_specs: InputSpecs = InputSpecs({
        'resource_set': InputSpec(ResourceSet,
                                  human_name="Input ResourceSet to filter",
                                  short_description="ResourceSet from FermentalgLoadData containing batch/sample tagged resources",
                                  optional=False),
    })

    output_specs: OutputSpecs = OutputSpecs({
        'filtered_resource_set': OutputSpec(ResourceSet,
                                            human_name="Filtered ResourceSet",
                                            short_description="ResourceSet containing only selected batch/sample combinations")
    })

    config_specs = ConfigSpecs({
        'selection_criteria': ListParam(
            human_name="Selection criteria with Batch/Sample pairs",
            short_description="List of dictionaries with 'batch' and 'sample' keys for filtering",
            optional=False
        )
    })

    def run(self, params: ConfigParams, inputs) -> Dict[str, Any]:
        resource_set: ResourceSet = inputs['resource_set']
        selection_criteria: List[Dict[str, str]] = params.get_value('selection_criteria')

        self.log_info_message(
            f"Filtering ResourceSet with {len(selection_criteria)} selected batch/sample combinations")

        # Create a new ResourceSet for filtered data
        filtered_res = ResourceSet()

        # Create selection criteria set for faster lookup
        selection_set = set()
        for criteria in selection_criteria:
            if type(criteria) != dict and type(criteria) == str:
                criteria = json.loads(criteria)
            batch = criteria.get(BATCH_TAG_KEY, '')
            sample_name = criteria.get(SAMPLE_TAG_KEY, '')
            selection_set.add((batch, sample_name))

        self.log_info_message(f"Selection criteria: {selection_set}")

        matched_count = 0
        total_resources = len(resource_set.get_resources())

        # Filter each resource in the ResourceSet based on tags
        for resource_name, resource in resource_set.get_resources().items():

            if not isinstance(resource, Table):
                self.log_debug_message(
                    f"⏭️ Skipping non-Table resource '{resource_name}'")
                continue

            if not resource.tags:
                self.log_warning_message(
                    f"⚠️ Resource '{resource_name}' has no tags and will be skipped")
                continue

            # Check if this resource matches any of the selected Batch/Sample pairs
            # by examining its tags
            should_include = False

            if resource.tags:
                batch_tag_value = None
                sample_tag_value = None

                # Extract Batch and Sample values from resource tags
                for tag in resource.tags.get_tags():
                    if tag.key == BATCH_TAG_KEY:
                        batch_tag_value = tag.value
                    elif tag.key == SAMPLE_TAG_KEY:
                        sample_tag_value = tag.value

                # Check if this resource's batch/sample combination matches selection criteria
                if batch_tag_value and sample_tag_value:
                    if (batch_tag_value, sample_tag_value) in selection_set:
                        should_include = True
                        self.log_info_message(
                            f"✅ Including resource '{resource_name}' - batch: '{batch_tag_value}', sample: '{sample_tag_value}'")
                    else:
                        self.log_debug_message(
                            f"⏭️ Skipping resource '{resource_name}' - batch: '{batch_tag_value}', sample: '{sample_tag_value}' not in selection")
                else:
                    self.log_warning_message(
                        f"⚠️ Resource '{resource_name}' missing required tags - batch: {batch_tag_value}, sample: {sample_tag_value}")

            # If this resource should be included, add it to filtered ResourceSet
            if should_include:
                # Create a copy of the resource to preserve all tags and properties
                filtered_table = Table(resource.get_data().copy())
                filtered_table.name = resource.name

                # Copy all original tags to ensure they are preserved
                if resource.tags:
                    for tag in resource.tags.get_tags():
                        filtered_table.tags.add_tag(Tag(key=tag.key, value=tag.value))

                for column_name in resource.get_column_names():
                    col_tags: Dict[str, str] = resource.get_column_tags_by_name(column_name)
                    for col_tag_key, col_tag_value in col_tags.items():
                        filtered_table.add_column_tag_by_name(column_name, col_tag_key, col_tag_value)

                # Add the filtered resource with preserved tags
                filtered_res.add_resource(filtered_table, resource_name)
                matched_count += 1

        self.log_success_message(f"Filtered {matched_count}/{total_resources} resources based on selection criteria")

        if matched_count == 0:
            self.log_warning_message(
                "No resources matched the selection criteria. Check that resources have proper 'batch' and 'sample' tags.")

        return {'filtered_resource_set': filtered_res}
