from gws_core import (
    AppConfig,
    AppType,
    ConfigParams,
    OutputSpec,
    OutputSpecs,
    StreamlitResource,
    Task,
    TaskInputs,
    TaskOutputs,
    app_decorator,
    task_decorator,
)


@app_decorator(
    "ConstellabBioprocessDashboardAppConfig",
    app_type=AppType.STREAMLIT,
    human_name="Generate Constellab Bioprocess Dashboard app",
)
class ConstellabBioprocessDashboardAppConfig(AppConfig):
    """
    Configuration class for the Constellab Bioprocess Dashboard Streamlit application.

    This class defines the configuration and setup for a Streamlit-based dashboard
    that provides visualization and analysis capabilities for Constellab Bioprocess data.
    """

    def get_app_folder_path(self):
        """Get the path to the app folder relative to this file."""
        return self.get_app_folder_from_relative_path(__file__, "_constellab_bioprocess_dashboard")


@task_decorator(
    "GenerateConstellabBioprocessDashboard",
    human_name="Generate Constellab Bioprocess Dashboard app",
    short_description="Create a Streamlit dashboard for Constellab Bioprocess data analysis",
    style=StreamlitResource.copy_style(),
)
class GenerateConstellabBioprocessDashboard(Task):
    """
    Task that generates the Constellab Bioprocess Dashboard app.
    This dashboard provides visualization and analysis capabilities for Constellab Bioprocess data.

    The Constellab Bioprocess Dashboard is a Streamlit application designed for fermentation data analysis
    and visualization from fermentors instruments. It provides an interactive interface for
    processing, analyzing, and interpreting data from fermentors experiments through various
    analytical workflows.

    The aim is to simplify the use of the fermentors data processing by providing an application
    that makes uploading, processing, and visualizing fermentation data easier.

    Features:

    - **File Upload Interface**: Upload Excel files generated by fermentors
    - **Data Processing**: Automated processing using BiolectorXT task
    - **Data Quality Assessment**: Identification of missing values and incomplete datasets
    - **Interactive Selection**: Choose specific samples for detailed analysis
    - **Data Visualization**: Multiple chart types including time series, box plots, histograms, and scatter plots
    - **Statistical Analysis**: Descriptive statistics and data summaries
    - **Batch Analysis**: Compare different fermentation batches and culture conditions

    The dashboard automatically processes uploaded files, identifies data quality issues,
    and provides an intuitive interface for selecting and visualizing specific datasets
    of interest for detailed analysis.
    """

    output_specs: OutputSpecs = OutputSpecs(
        {"dashboard": OutputSpec(StreamlitResource, human_name="Constellab Bioprocess Dashboard")}
    )

    def run(self, params: ConfigParams, inputs: TaskInputs) -> TaskOutputs:
        """Generate and return the Constellab Bioprocess Dashboard Streamlit application."""
        dashboard = StreamlitResource()
        dashboard.set_app_config(ConstellabBioprocessDashboardAppConfig())
        dashboard.name = "Constellab Bioprocess"

        return {"dashboard": dashboard}
