import os
from gws_core import (
    ConfigParams, AppConfig, AppType, OutputSpec, OutputSpecs, StreamlitResource, Task, TaskInputs, TaskOutputs,
    app_decorator, task_decorator, TypingStyle
)


@app_decorator("GreencellFermentorDashboardAppConfig", app_type=AppType.STREAMLIT,
               human_name="Generate Greencell Fermentor Dashboard app")
class GreencellFermentorDashboardAppConfig(AppConfig):
    """
    Configuration class for the Greencell Fermentor Dashboard Streamlit application.

    This class defines the configuration and setup for a Streamlit-based dashboard
    that provides visualization and analysis capabilities for Greencell Fermentor data.
    """

    def get_app_folder_path(self):
        """Get the path to the app folder relative to this file."""
        return self.get_app_folder_from_relative_path(__file__, "_greencell_fermentor_dashboard")


@task_decorator("GenerateGreencellFermentorDashboard", human_name="Generate Greencell Fermentor Dashboard app",
                short_description="Create a Streamlit dashboard for Greencell Fermentor data analysis",
                style=StreamlitResource.copy_style())
class GenerateGreencellFermentorDashboard(Task):
    """
    Task that generates the Greencell Fermentor Dashboard app.
    This dashboard provides visualization and analysis capabilities for Greencell Fermentor data.

    The Greencell Fermentor Dashboard is a Streamlit application designed for fermentation data analysis
    and visualization from Greencell Fermentor instruments. It provides an interactive interface for
    processing, analyzing, and interpreting data from Greencell Fermentor experiments through various
    analytical workflows.

    The aim is to simplify the use of the Greencell Fermentor data processing by providing an application
    that makes uploading, processing, and visualizing fermentation data easier.

    Features:

    - **File Upload Interface**: Upload Excel files generated by Greencell Fermentor
    - **Data Processing**: Automated processing using BiolectorXT task
    - **Data Quality Assessment**: Identification of missing values and incomplete datasets
    - **Interactive Selection**: Choose specific samples for detailed analysis
    - **Data Visualization**: Multiple chart types including time series, box plots, histograms, and scatter plots
    - **Statistical Analysis**: Descriptive statistics and data summaries
    - **Batch Analysis**: Compare different fermentation batches and culture conditions

    Required Input File:
    - Biolector Excel File: .xlsx or .xls file generated by Biolector XT containing measurement data

    The dashboard automatically processes uploaded files, identifies data quality issues,
    and provides an intuitive interface for selecting and visualizing specific datasets
    of interest for detailed analysis.
    """

    output_specs: OutputSpecs = OutputSpecs({
        'dashboard': OutputSpec(StreamlitResource, human_name="Greencell Fermentor Dashboard")
    })

    def run(self, params: ConfigParams, inputs: TaskInputs) -> TaskOutputs:
        """Generate and return the Greencell Fermentor Dashboard Streamlit application."""
        dashboard = StreamlitResource()
        dashboard.set_app_config(GreencellFermentorDashboardAppConfig())

        return {"dashboard": dashboard}
